# Generated by Django 4.1.13 on 2024-03-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Информация об авторе"},
        ),
    ]
